name: CI

on: [pull_request, push]  # Disabled - workflow will only run manually via workflow_dispatch
# on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/systemcore-cross-ubuntu:2025-22.04
            artifact-name: SystemCore
            target-arch: arm64
            llvm-version: "20.1.7"
            build-options: -Pplatform=linux-systemcore -Ptoolchain=/usr/local/toolchain-config.cmake
          - container: wpilib/aarch64-cross-ubuntu:bookworm-22.04
            artifact-name: Arm64
            target-arch: arm64
            llvm-version: "20.1.7"
            build-options: -Pplatform=linux-arm64 -Ptoolchain=/usr/local/toolchain-config.cmake
          - container: wpilib/ubuntu-base:22.04
            artifact-name: Linux
            target-arch: x64
            llvm-version: "20.1.7"
            build-options: -Pplatform=linux-x86_64

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.8
        with:
          version: ${{ matrix.llvm-version }}
          arch: ${{ matrix.target-arch }}
      - name: Install Dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y ninja-build build-essential libtbb-dev libzstd-dev
      - run: ls -R
      - name: Build with Gradle
        run: ./gradlew publish -PllvmPath="${{ env.LLVM_PATH }}" ${{ matrix.build-options }}
        # env:
        #   SCCACHE_WEBDAV_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        #   SCCACHE_WEBDAV_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: gradleDir/outputs/

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact-name: Win64
            runs-on: windows-2022
            tool-arch: amd64
            build-options: -Pplatform=windows-x86_64
            llvm-version: "20.1.7"
            java-version: 17
          - artifact-name: WinArm64
            runs-on: windows-11-arm
            tool-arch: amd64_arm64
            build-options: -Pplatform=windows-arm64
            llvm-version: "20.1.7"
            java-version: 21

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.tool-arch }}
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.8
        with:
          version: ${{ matrix.llvm-version }}
      - name: Build with Gradle
        run: ./gradlew publish -PllvmPath="${{ env.LLVM_PATH }}" ${{ matrix.build-options }}
        # env:
        #   SCCACHE_WEBDAV_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        #   SCCACHE_WEBDAV_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: gradleDir/outputs/

  build-mac:
    name: "Build - macOS"
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.8
        with:
          version: "20.1.7"
          env: true
      - run: brew install cmake ninja
        name: install ninja
      - name: Build with Gradle
        run: ./gradlew publish -Pplatform=osx-universal -PllvmPath="${{ env.LLVM_PATH }}"
        # env:
        #   SCCACHE_WEBDAV_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        #   SCCACHE_WEBDAV_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: gradleDir/outputs/

  combine:
    name: Combine
    needs: [build-docker, build-windows, build-mac]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wpilibsuite/build-tools
      - uses: actions/download-artifact@v4
        with:
          path: combiner/products/build/allOutputs
      - name: Flatten Artifacts
        run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/
      - name: Combine
        if: |
          github.repository_owner == 'wpilibsuite' &&
          !startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publish -Pthirdparty
        working-directory: combiner
      - name: Combine (Release)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publish -Pthirdparty
        # env:
        #   RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
        #   ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        #   ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        working-directory: combiner
      - uses: actions/upload-artifact@v4
        with:
          name: Maven
          path: ~/releases
